### PR TITLE
Update goja

### PR DESCRIPTION
**Pull request by joanlopez**
* Added support for separators in numeric literals.

* Improved support for Unicode code point escapes (\u{...}) in regexes.

* Improved number parsing compatibility.

---------

### CODE REVIEW

**Review by olegbespalov — APPROVED** [review]
:rocket:

**Comment by mstoykov** [comment]
I prefer that you do a merge commit here directly with the master branch from goja.

In this way the next time this code gets changed you don't need to cherry-pick and merge conflict fix changes.

Given how common it is for fixes or even feature additions to touch across multiple places, making it easy to not have merge conflicts seems like a must if we want to do this more.

**Comment by joanlopez** [comment]
> I prefer that you do a merge commit here directly with the master branch from goja.
> 
> In this way the next time this code gets changed you don't need to cherry-pick and merge conflict fix changes.
> 
> Given how common it is for fixes or even feature additions to touch across multiple places, making it easy to not have merge conflicts seems like a must if we want to do this more.

Sure, of course! Like now? 🤔

**Comment by mstoykov** [comment]
Yeah and also the "merge pull request" so again .. git can figure out the merge conflict resolution later

**Review by mstoykov — APPROVED** [review]

**Pull request merged**
